---

#linux_server:
# hosts:
#   test_server:
#     ansible_host: 141.94.106.69
#     ansible_user: ubuntu

linux_central:
  hosts:
    test_server:
      ansible_host: 152.228.211.254
      ansible_user: ubuntu
