---

linux_server:
  hosts:
    test_server:
      ansible_host: 141.94.106.69
      ansible_user: ubuntu

linux_central:
  hosts:
    test_server:
      ansible_host: 141.94.106.69
      ansible_user: ubuntu
