---

- hosts:
    - linux_server
      #    - windows_server
  vars:
    zerotier_network_id: 14b391f78dc89249 
  roles:
    - m4rcu5nl.zerotier-one
- hosts:
    - linux_central
  roles:
    - docker
    - zerotier-controller
