---

- hosts:
  - linux_server
  - windows_server
   #vars:
     #zerotier_network_id:
  roles:
    - m4rcu5nl.zerotier-one
- hosts:
    - linux_central
  roles:
    - docker
    - zerotier-controller
    - xanmanning.k3s
